name: Docker CI (APT)

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup Matrix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set APT matrix
        id: apt-ppa
        run: |
          APT=$(jq -n '.include |= [ inputs[] | select(.["exclude"] != true)]' apt/*.json --compact-output)
          echo "apt=${APT}" >> $GITHUB_OUTPUT

    outputs:
      apt-matrix: ${{ steps.apt-ppa.outputs.apt }}

  build:
    name: ${{ matrix.description }}
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      SECRET_DOCKER_CI: ${{ secrets.DOCKER_CI }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.apt-matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set lower case actor name for docker build
        run: |
          echo "ACTOR_LC=${ACTOR,,}" >> ${GITHUB_ENV}
        env:
          ACTOR: '${{ github.actor }}'

      - name: Build and tag docker image
        run: |
          if [ '${{ github.repository }}' == 'hyperion-project/hyperion.docker-ci' ]; then
            docker build -t ghcr.io/hyperion-project/${{ matrix.file }}:${{ matrix.tag }} --build-arg DIST=${{ matrix.dist }} --build-arg SUITE=${{ matrix.tag }} -f apt/${{ matrix.file }} .
          else
            docker build -t ghcr.io/${{ env.ACTOR_LC }}/${{ matrix.file }}:${{ matrix.tag }} --build-arg DIST=${{ matrix.dist }} --build-arg SUITE=${{ matrix.tag }} --build-arg REPOSITORY="${{ github.server_url }}/${{ github.actor }}" -f apt/${{ matrix.file }} .
          fi

      - name: Publish to GitHub Container/Package Registry
        if: ${{ env.SECRET_DOCKER_CI != null }}
        run: |
          echo ${{ secrets.DOCKER_CI }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          if [ '${{ github.repository }}' == 'hyperion-project/hyperion.docker-ci' ]; then
            docker push ghcr.io/hyperion-project/${{ matrix.file }}:${{ matrix.tag }}
          else
            docker push ghcr.io/${{ env.ACTOR_LC }}/${{ matrix.file }}:${{ matrix.tag }}
          fi
